In [1]:
# 1. What is a Python library? Why do we use Python libraries?

# Explanation:
# A Python library is a collection of modules (files with Python code) that help us perform common tasks.
# Libraries provide functions and classes to simplify complex tasks like numerical computations, file handling, and data manipulation.

# Why use Python libraries?
# - They save time and effort by providing pre-built, reusable code.
# - They allow us to perform complex operations easily and efficiently.
# - They contain optimized implementations for performance.

# Example: Importing a library and using its functions
import numpy as np

# Creating a simple NumPy array
arr = np.array([1, 2, 3, 4])
arr


array([1, 2, 3, 4])

In [2]:
# 2. What is the difference between Numpy array and List?

# NumPy Array:
# - Stores elements of the same data type.
# - More efficient for numerical operations.
# - Supports multi-dimensional arrays (e.g., 2D, 3D).
# - Allows vectorized operations, which are faster.

# Python List:
# - Can store elements of different data types.
# - Less efficient for numerical computations.
# - Primarily 1D, although it can be nested to simulate multi-dimensional lists.
# - Does not support vectorized operations.

# Example: Comparing NumPy Array with a Python List
py_list = [1, 2, 3, 4]
np_array = np.array([1, 2, 3, 4])

# Display the type of both
type(py_list), type(np_array)


(list, numpy.ndarray)

In [3]:
# 3. Find the shape, size, and dimension of the following array:
# [[1, 2, 3, 4],
#  [5, 6, 7, 8],
#  [9, 10, 11, 12]]

# Creating the array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Finding shape, size, and dimension
shape = array.shape
size = array.size
dimension = array.ndim

shape, size, dimension


((3, 4), 12, 2)

In [4]:
# 4. Write python code to access the first row of the following array:
# [[1, 2, 3, 4],
#  [5, 6, 7, 8],
#  [9, 10, 11, 12]]

# Accessing the first row of the array
first_row = array[0]
first_row


array([1, 2, 3, 4])

In [5]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
# [[1, 2, 3, 4],
#  [5, 6, 7, 8],
#  [9, 10, 11, 12]]

# Accessing the element at the third row and fourth column
element = array[2, 3]
element


12

In [6]:
# 6. Write code to extract all odd-indexed elements from the given numpy array:
# [[1, 2, 3, 4],
#  [5, 6, 7, 8],
#  [9, 10, 11, 12]]

# Extracting odd-indexed elements (odd rows and odd columns)
odd_indexed_elements = array[::2, ::2]
odd_indexed_elements


array([[ 1,  3],
       [ 9, 11]])

In [7]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

# Generating a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)
random_matrix


array([[0.19953066, 0.90979398, 0.24983745],
       [0.38127543, 0.45243513, 0.64797595],
       [0.52527842, 0.72402148, 0.09457946]])

In [8]:
# 8. Describe the difference between np.random.rand and np.random.randn?

# np.random.rand:
# - Generates random numbers from a uniform distribution in the range [0, 1).
# np.random.randn:
# - Generates random numbers from a standard normal distribution (mean=0, std=1).

# Example:
rand_example = np.random.rand(3, 3)   # Uniform distribution between 0 and 1
randn_example = np.random.randn(3, 3)  # Standard normal distribution
rand_example, randn_example


(array([[0.15795379, 0.99301072, 0.88996594],
        [0.50420921, 0.78568081, 0.25000206],
        [0.75352997, 0.57102986, 0.0988946 ]]),
 array([[ 0.04224724, -0.83624554,  0.91935733],
        [ 1.19638683, -1.39093401,  0.17454531],
        [-0.55264509, -0.11705334,  1.2410504 ]]))

In [9]:
# 9. Write code to increase the dimension of the following array:
# [[1, 2, 3, 4],
#  [5, 6, 7, 8],
#  [9, 10, 11, 12]]

# Expanding the dimension of the array
expanded_array = np.expand_dims(array, axis=0)
expanded_array


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [10]:
# 10. How to transpose the following array in NumPy?
# [[1, 2, 3, 4],
#  [5, 6, 7, 8],
#  [9, 10, 11, 12]]

# Transposing the array (rows become columns)
transposed_array = array.T
transposed_array


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [11]:
# 11. Perform matrix operations:

# Matrix A:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Matrix B:
B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Index-wise addition
addition = A + B

# Index-wise multiplication
multiplication = A * B

# Matrix multiplication (Dot product)
matrix_multiplication = np.dot(A, B.T)  # A dot B transpose

# Add both matrices
matrix_addition = np.add(A, B)

# Subtract matrix B from matrix A
matrix_subtraction = np.subtract(A, B)

# Divide matrix B by matrix A (element-wise division)
matrix_division = np.divide(B, A)

addition, multiplication, matrix_multiplication, matrix_addition, matrix_subtraction, matrix_division


(array([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]]),
 array([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]]),
 array([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]]),
 array([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]]),
 array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [12]:
# 12. Which function in Numpy can be used to swap the byte order of an array?

# The function to swap the byte order is np.byteswap().
# Example:
array = np.array([1, 2, 3, 4], dtype='>i4')  # Big-endian byte order
swapped_array = array.byteswap().newbyteorder()
swapped_array


array([1, 2, 3, 4], dtype=int32)

In [13]:
# 13. What is the significance of the np.linalg.inv function?

# The np.linalg.inv function computes the inverse of a matrix.
# Example:
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
A_inv


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [15]:
# 14. What does the np.reshape function do, and how is it used?

# np.reshape changes the shape of an array without changing its data.
# Example:
# Create an array with 12 elements (since 4 * 3 = 12)
array_large = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshaping the array to 4 rows and 3 columns
reshaped_array_large = np.reshape(array_large, (4, 3))

reshaped_array_large


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
# 15. What is broadcasting in Numpy?

# Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes.
# The smaller array is "broadcast" over the larger array, so they have compatible shapes for arithmetic operations.

# Example:
array_1 = np.array([1, 2, 3])
array_2 = np.array([[1], [2], [3]])

# Broadcasting array_2 to the shape of array_1
result = array_1 + array_2
result


array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])